$(document).ready(function(){
		$("#register").click(function(){
			$("#signupModal").modal();
		});
});
$(document).ready(function(){
		$("#login").click(function(){
			$("#loginModal").modal();
		});
});
